// Code generated by Prismic. DO NOT EDIT.

import CallToAction from "./CallToAction";
import Footer from "./Footer";
import Hero from "./Hero";
import Projetos from "./Projetos";
import QuemSomos from "./QuemSomos";

export const components = {
	call_to_action: CallToAction,
	footer: Footer,
	hero: Hero,
	projetos: Projetos,
	quem_somos: QuemSomos
};